name: google_maps_place_picker
description: A Flutter plugin which provides 'Picking Place' using Google Maps widget.
version: 2.0.0-nullsafety.3
homepage: https://github.com/fysoul17/google_maps_place_picker

environment:
  sdk: ">=2.17.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  provider: ^6.0.5
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_api_headers: ^2.0.3
  tuple: ^2.0.2
  http: ^0.13.0
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
